[package]
name = "rust-todo"
version = "0.1.0"
authors = ["KDH <ehdgua01@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.0"

[[bin]]
name = "rust-todo"
path = "src/main.rs"
